// Copyright (c) 2023 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=9cac66f9a5b9b95e989b4202be9163eed6672851$
//

#ifndef CEF_LIBCEF_DLL_CTOCPP_AUTHENTICATOR_REQUEST_CALLBACK_CTOCPP_H_
#define CEF_LIBCEF_DLL_CTOCPP_AUTHENTICATOR_REQUEST_CALLBACK_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_authenticator_request_callback_capi.h"
#include "include/cef_authenticator_request_callback.h"
#include "libcef_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefAuthenticatorRequestCallbackCToCpp
    : public CefCToCppRefCounted<CefAuthenticatorRequestCallbackCToCpp,
                                 CefAuthenticatorRequestCallback,
                                 cef_authenticator_request_callback_t> {
 public:
  CefAuthenticatorRequestCallbackCToCpp();
  virtual ~CefAuthenticatorRequestCallbackCToCpp();

  // CefAuthenticatorRequestCallback methods.
  void Continue(const CefString& pin) override;
  void Cancel() override;
};

#endif  // CEF_LIBCEF_DLL_CTOCPP_AUTHENTICATOR_REQUEST_CALLBACK_CTOCPP_H_
